
name: Check and udpate Ingress-Nginx Helm chart version

on:
  schedule:
    - cron: '0 9 * * 1'

# on:
#   pull_request:
#     types:
#       - opened
#       - reopened
#       - synchronize
#     branches:
#       - master

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Format Terraform scripts
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Initialize Terraform
      id: init
      run: terraform init
    
    - name: Validate Terraform scripts
      id: validate
      run: terraform validate -no-color
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Get latest Helm chart version from ArtifactHub
      id: get_latest_version
      run: |
        latest_version=$(curl -s https://artifacthub.io/api/v1/packages/helm/ingress-nginx/ingress-nginx | jq -r '.version')
        echo "Latest ingress-nginx version: $latest_version"
        echo "latest_version=$latest_version" >> $GITHUB_ENV

    - name: Update version in variables.tf if necessary
      id: compare_versions
      run: |
        terraform plan -out=tfplan
        terraform show -json tfplan > plan.json
        current_version=$(jq -r '.variables.nginx_ingress_chart_version.value' plan.json)
        latest_version="${{ env.latest_version }}"
        echo "Current version: $current_version"
        echo "update_version=false" >> $GITHUB_ENV
        cat variables.tf | grep -A 4 -B 4 nginx_ingress_chart_version
        if [[ "$latest_version" != "$current_version" ]]; then
          echo "update_version=true" >> $GITHUB_ENV
          echo "New version found, updating to $latest_version"
          sed -i "s/$current_version/$latest_version/" variables.tf
        else
          echo "Already up-to-date"
        fi
        cat variables.tf | grep -A 4 -B 4 nginx_ingress_chart_version

    - name: Install terraform-docs
      id: docs
      if: env.update_version == 'true'
      run: |
        curl -sSLo terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
        tar -xzf terraform-docs.tar.gz
        chmod +x terraform-docs
        sudo mv terraform-docs /usr/local/bin/
        terraform-docs markdown table --output-file README.md ./

    - name: Get latest tag
      id: get_latest_tag
      if: env.update_version == 'true'
      run: |
        git fetch --tags
        latest_tag=$(git tag --sort=-v:refname | head -n 1)
        echo "Latest tag: $latest_tag"
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV

    - name: Increment version
      id: increment_version
      if: env.update_version == 'true'
      run: |
        IFS='.' read -r major minor patch <<< "${{ env.latest_tag }}"
        new_patch=$((patch + 1))
        new_tag="$major.$minor.$new_patch"
        echo "New version: $new_tag"
        echo "new_tag=$new_tag" >> $GITHUB_ENV

    - name: Commit changes
      if: env.update_version == 'true'   
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git status
        git commit -m "Update module to nginx controller chart version - ${{ env.latest_version }}"

    - name: Tag the new version
      if: env.update_version == 'true'
      run: |
        git tag ${{ env.new_tag }}

    - name: Push changes and tags
      if: env.update_version == 'true'
      run: |
        # Push both the commit and the tags to the master branch
        git push origin master
        git push origin master --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}